development:
  adapter: async
  url: "http://localhost:3000"

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: CableChat_production
